apiVersion: v1
kind: Service
metadata:
  name: {{ include "api.fullname" . }}
  labels:
    app: {{ include "api.name" . }}
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: {{ .Values.service.nodePort }}
  selector:
    app: {{ include "api.name" . }}
