name: CI/CD Pipeline

on:
  push:
    branches:
      - '**'
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Change directory to project root
        working-directory: ./vdt2024
        run: pwd

      - name: Grant execute permission for gradlew
        working-directory: ./vdt2024
        run: chmod +x gradlew

      - name: Build with Gradle
        working-directory: ./vdt2024
        run: ./gradlew build

      - name: Run unit tests
        working-directory: ./vdt2024
        run: ./gradlew test

  cd:
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/')

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: minhitptit
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: ./vdt2024  # Specify the path to your Dockerfile
          file: ./vdt2024/Dockerfile  # Specify the path to your Dockerfile
          push: true
          tags: minhitptit/api:${{ github.ref_name }}

      - name: Checkout config repo
        uses: actions/checkout@v2
        with:
          repository: Minh141120/api-config
          token: ${{ secrets.GITHUB_TOKEN }}
          path: api-config

      - name: Update image tag in values.yaml
        run: |
          cd api-config
          sed -i "s/tag:.*/tag: ${{ github.ref_name }}/" values.yaml
          git config --global user.email "minh.itptit@gmail.com"
          git config --global user.name "Minh141120"
          git add values.yaml
          git commit -m "Update image tag to ${{ github.ref_name }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
