name: CI/CD Pipeline

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: minhitptit
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: minhitptit/api:${{ github.ref_name }}

  update-values:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout config repo
        uses: actions/checkout@v2
        with:
          repository: Minh141120/api-config
          token: ${{ secrets.GH_PAT }}
          path: api-config

      - name: Update image tag in values.yaml
        run: |
          cd api-config
          sed -i "s/tag:.*/tag: ${{ github.ref_name }}/" values.yaml
          git config --global user.email "minh.itptit@gmail.com"
          git config --global user.name "Minh141120"
          git add values.yaml
          git commit -m "Update image tag to ${{ github.ref_name }}"
          git push https://Minh141120:${{ secrets.GH_PAT }}@github.com/Minh141120/api-config.git HEAD:main
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
